### ISSUE TITLE
Trobar lloc per a la xerrada del 27 de Febrer

### ISSUE THREAD

**Issue by EsteveAguilera** [InformaticsEmporda/Xerrades#1]
Requisits mínims:
- Projector
- Gratis

Preferiblement:
- Bar a prop per al networking post-xerrada 🍻 
- A prop del centre
- Bon accés amb cotxe i pàrking

**Comment by ctrl-alt-d** [comment]
hola l'Esteva va parlar de la disponibilitat de la sala Empordà Networking (?). Hi ha espai per aparcar, tema bar no està tant clar crec. No sé si encara està l'oferta en peu.

Altres sales poden ser la cate, crec que té una sala petita, no recordo. O 'el pati' si som colla i ens quedem a sopar. Jo a aquella hora tinc molta gana .

**Comment by EsteveAguilera** [comment]
Avui he parlat amb el propietàri del Empordà Cowork, i em confirma que demà està previt finalitzar les reformes de la sala de reunions.

Té una capacitat de 20 persones amb cadira, i algunes més de peu 😅 , i disposaríem de projector.

**Comment by magarrent** [comment]
A Empordà Cowork estaria molt be, no es molt centric però no hi ha problema per aparcar. També hi ha bar al costat :D

**Comment by EsteveAguilera** [comment]
Comparteixo la ubicació del Empordà Cowork per si algú no el coneix:

https://www.google.es/maps/place/Emporda+Cowork/@42.2583604,2.9577309,18z/data=!3m1!4b1!4m5!3m4!1s0x12ba8dc014c7dc1f:0x757f19e7680433eb!8m2!3d42.2583604!4d2.9587698

Tema bars està un pél xungo... em sembla que tanquen força aviat els dos que hi ha per la zona....

**Comment by ctrl-alt-d** [comment]
Resolt :) El 27 ens trobem allà. Gràcies Esteve, gràcies Empordà Cowork.
