### ISSUE TITLE
Feedback xerrada 27 febrer 2018

### ISSUE THREAD

**Issue by EsteveAguilera** [InformaticsEmporda/Xerrades#14]
Un cop finalitzada la xerrada, toca recopilar feedback per a intentar millorar de cares a la propera!

Tot tipus de feedback serà benvingut!

**Comment by ctrl-alt-d** [comment]
Hem de ser múltiples de 5, la resta tot va anar perfecte. Jo ja he començat a fer servir dockers. No oblideu posar el vostre usuari al grup docker per no haver de fer sudo. Gràcies [xavi](https://github.com/utrescu) per la xerrada!

**Comment by EsteveAguilera** [comment]
Tanco la issue, gràcies per el feedback aportat!
