### ISSUE TITLE
Desenvolupar amb Docker: Linux ha enamorat Microsoft

### ISSUE THREAD

**Issue by utrescu** [InformaticsEmporda/Xerrades#5]
### Proposta

- [ ] Proposo que algú faci una xerrada
- [X] Vull fer una xerrada
- [ ] Conec algú que la pot fer

#### Breu descripció
Que Docker ha afegit grans avantatges a l'hora de desplegar aplicacions és bastant conegut però també n'ha afegit a l'hora de desenvolupar les aplicacions.  La idea és mostrar els avantatges que aporta des del punt de vista dels desenvolupadors d'aplicacions

**Comment by EsteveAguilera** [comment]
Tanto la issue, xerrada feta! 🎆
