### ISSUE TITLE
Desenvolupament d'App amb tecnologia web

### ISSUE THREAD

**Issue by utrescu** [InformaticsEmporda/Xerrades#7]
### Proposta

- [ ] Proposo que algú faci una xerrada
- [x] Vull fer una xerrada
- [ ] Conec algú que la pot fer

#### Breu descripció
Fins ara quan es volien  desenvolupar APP mòbils que es puguin executar en tots els dispositius implicava desenvolupar, almenys, dues aplicacions diferents: una per Android i una per IOS.  Els coneixements necessaris per fer-ho han estat una barrera important per als desenvolupadors web... 

Es pot aprofitar el que els desenvolupadors web ja saben fer per crear APPs multiplataforma? El món s'acaba... Desenvolupadors web fent APPs!

**Comment by seicoll** [comment]
M'agrada aquesta proposta!

**Comment by EsteveAguilera** [comment]
Xerrada realitzada el 24 d'Abril del 2018

https://github.com/InformaticsEmporda/Xerrades/tree/master/xerrades/2018-04-24
